10 basic map component
ctc-uci/find-your-anchor-frontend pull request #12
Opened 2021-11-29 06:33 UTC by ctc-devops

- Integrate Leaflet API into webapp
- Add map component onto dashboard (root page)
- Test key functionality and map components (e.g. how to add markers/pins on the map, searching for a specific location, zooming in/out of the map, etc). It would be helpful to document anything you find that is useful.
closes #10

2021-11-29 07:20 UTC, ctc-devops commented on public/index.html
> +      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
🚫 **[detect-secrets]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>
* Base64 High Entropy String

2021-11-29 07:21 UTC, ctc-devops commented on src/components/Map.jsx
> +              console.log(`hovered over ${obj.id}`);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2021-12-01 17:50 UTC, claudeisakeeb commented on src/components/Map.jsx
> +              console.log(`hovered over ${obj.id}`);
Hover effect was removed

2021-12-01 17:51 UTC, claudeisakeeb commented on public/index.html
> +      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
This stylesheet is one that anyone who uses leaflet would know about so I don't think it's a "secret." We can delete it and find another way to import the styling if really necessary though.

2021-12-04 01:01 UTC, meghakak requested changes
Couple nits and then this should be good to go. Awesome job on integrating the API and adding well documented comments along the way! :)

2021-12-04 01:01 UTC, meghakak commented on src/components/Map/Map.jsx
> +  const markerCoords = [
Could you add a comment here about using Nominatim for conversion (along with a link please)?

2021-12-04 01:01 UTC, meghakak commented on src/components/Map/Map.jsx
> +      // autoClose: true
nit: If this is unnecessary, please remove the commented code

2021-12-04 01:01 UTC, meghakak commented on src/components/Map/Map.jsx
> +      {markerCoords.map(obj => (
super nit: By industry standards, it's always better to name variables without abbreviations, acronyms, etc and instead use the full name to avoid any confusion. So for this case, please use "object" instead of "obj."

2021-12-04 01:01 UTC, meghakak commented on src/components/Map/Map.jsx
> +      {markerCoords.map(obj => (
Personally, I would even name this "markerCoord" or "markerObject" to clarify. This makes legacy code much easier to understand in the future.

2021-12-04 01:01 UTC, meghakak commented on public/index.html
> +      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
I think it's best to just make the integrity value an env variable. Even though this is publicly accessible online, it might confuse a future developer since it does look like a secret value. Let's wait for Sylvester's thoughts on this before making any changes.

2021-12-04 03:10 UTC, claudeisakeeb commented on src/components/Map/Map.jsx
> +  const markerCoords = [
Added

2021-12-04 03:10 UTC, claudeisakeeb commented on src/components/Map/Map.jsx
> +      // autoClose: true
Removed

2021-12-04 03:10 UTC, claudeisakeeb commented on src/components/Map/Map.jsx
> +      {markerCoords.map(obj => (
yes inject that google knowledge into my veins....

Renamed markerCoords to markerData and obj to markerObject

2021-12-05 06:36 UTC, meghakak commented on src/components/Map/Map.jsx
> +      {markerCoords.map(obj => (
this comment was left on so many of my code reviews last summer lol it's ingrained in my brain for life
thanks for making the change :)

2021-12-05 06:38 UTC, meghakak commented
Can you merge dev into this branch? This should fix the eslint issue.

2021-12-12 20:49 UTC, meghakak approved these changes, later dismissed
LGTM (other than the unresolved comment on the Leaflet API key). Thanks for making the changes earlier!

2022-01-09 19:56 UTC, sylvesteryue approved these changes
LGTM

2022-01-09 20:13 UTC, meghakak approved these changes
LGTM

2022-01-09 20:13 UTC, merged