Added mobile view for navbar
ctc-uci/find-your-anchor-frontend pull request #129
Opened 2022-04-17 18:01 UTC by jeffcheema

Added mobile views for navbar, used a modal component.

2022-04-19 04:19 UTC, claudeisakeeb requested changes
Nice work with the popup, lmk if you need any help with the comments I left

2022-04-19 04:19 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +import {
According to the Figma the general user dashboard should have:
- Dashboard
- About
- Launch a Box
- Found a Box
- Admin Login

Can we have all of these with the icons as specified on the Figma? You can download the icons from the Figma if react-icons doesn't have them

2022-04-19 04:19 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
>  import React, { useState, useEffect } from 'react';
I think the navbar elements should be more centered, text should be bigger, and there should be more padding between the icons and labels

2022-04-19 04:19 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +  IconButton,
When the screen is wide enough the icons won't be hamborgur design which I believe it should be? Maybe ask design if unsure. You can fix this by making these links flex-direction: column
![image](https://user-images.githubusercontent.com/47193525/163918963-da7270f3-8537-45d6-9015-33541bd5b9a9.png)

2022-04-19 04:19 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +  useDisclosure,
The admin dashboard should have:
- Admin Dashboard
- Add Box
- Upload CSV
- Export CSV
- User Profile
- Review Submissions
- Logout

Can we have all of these with the icons as specified on the Figma? You can download the icons from the Figma if react-icons doesn't have them

2022-04-19 04:19 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +              icon={<HamburgerIcon />}
Would it be possible to make the hamburger icon blend in with the navbar and a bit bigger?

2022-04-22 01:16 UTC, sylvesteryue commented on src/components/NavBar/NavBar.jsx
> +  useDisclosure,
Also, a note is that to make sure to change the order of the links around because currently you have user profile at the top

2022-05-04 02:35 UTC, ctc-devops commented on src/components/AdminProfile/LogoutModal/LogoutModalContent.jsx
> +    console.log(cookies);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-04 03:58 UTC, ctc-devops commented on src/components/NavBar/NavBar.jsx
> +import aboutIcon from '../../assets/navBarIcons/about-icon.svg';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module '../../assets/navBarIcons/about-icon.svg'.

2022-05-04 03:58 UTC, ctc-devops commented on src/components/NavBar/NavBar.jsx
> +import admingLoginIcon from '../../assets/navBarIcons/admin-login-icon.svg';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module '../../assets/navBarIcons/admin-login-icon.svg'.

2022-05-04 03:58 UTC, ctc-devops commented on src/components/NavBar/NavBar.jsx
> +    console.log('useeffect!');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-04 04:42 UTC, claudeisakeeb approved these changes
console.log('LGTM')

2022-05-04 04:42 UTC, claudeisakeeb commented on src/components/AdminProfile/LogoutModal/LogoutModalContent.jsx
> +    console.log(cookies);
remove

2022-05-04 04:42 UTC, claudeisakeeb commented on src/components/NavBar/NavBar.jsx
> +    console.log('useeffect!');
console.log('remove!')

2022-05-05 07:26 UTC, sylvesteryue approved these changes
litty goody tipsy mooody

2022-05-05 07:26 UTC, merged