dg box approval section
ctc-uci/find-your-anchor-frontend pull request #13
Opened 2021-12-04 01:13 UTC by ctc-devops

- Develop frontend component for approval/denied section on the Admin Dashboard page
- Build a separate component for the individual Box Information with all the details listed on the mockup
- [Figma Sheet](https://www.figma.com/file/y30pb19CamcegHG7Oh4lJC/FYA-Low-Fidelity-Wireframes)
closes #11

2021-12-05 07:30 UTC, meghakak requested changes
Great work on this sprint! Left a couple comments for small things to fix. Let me know if you have any questions about them :)

2021-12-05 07:30 UTC, meghakak commented on src/components/BoxApproval/BoxApproval.jsx
> +            width="100%"
Currently, these two buttons show up as longer than the box approval component on my screen. I believe changing the width for both of these to 50% should fix this issue. Please try to resize your screen to make sure this (and other styling) looks good after this change.

2021-12-05 07:30 UTC, meghakak commented on src/components/BoxApproval/BoxApproval.jsx
> +          <Button
In general, we want to separate our css styling and html/react components so let's move the styling on the buttons to the css file. Please do the same for Box.jsx.

2021-12-05 07:30 UTC, meghakak commented on src/components/BoxApproval/Box.jsx
> +        <Button size="xs" className="approveButton">
Could we change the "No" and "Yes" to X and checkmark icons as shown in the Figma? Y'all can use the Chakra icons for now: https://chakra-ui.com/docs/media-and-icons/icon

2021-12-05 07:30 UTC, meghakak commented on src/components/BoxApproval/Box.jsx
> +        <Text>ID</Text>
The ID has an extra space below it. Setting margin-bottom to 0 should fix this!

2021-12-12 19:39 UTC, dgardezi commented
I updated the code quite a bit to try and make things cleaner, but I believe all of the issues you addressed are fixed! Let me know if there is anything else to edit.

2021-12-12 20:47 UTC, meghakak approved these changes
LGTM! Thanks for making those changes, code looks much cleaner :)

2022-01-07 01:24 UTC, sylvesteryue approved these changes
LGTM as well!

2022-01-07 01:25 UTC, merged