51 common alert banner
ctc-uci/find-your-anchor-frontend pull request #130
Opened 2022-04-17 18:24 UTC by jeffcheema

Added err.message state and fixed toast after uploaded csv.

2022-04-20 00:41 UTC, claudeisakeeb requested changes
Toasts look good but upload csv and export csv both break for me.

Could you please merge dev into your branch and re-request review?

2022-04-20 00:41 UTC, claudeisakeeb commented on src/components/RelocationBox/RelocationBox.jsx
>  import { BsFillArrowRightCircleFill, BsFillCheckCircleFill, BsXCircleFill } from 'react-icons/bs';
Can we remove the alert in utils.jsx now that we have toasts for the email?

2022-04-20 00:41 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
> +    navigate(`/admin`);
This should navigate to root bc /admin doesn't exist anymore

2022-04-20 00:41 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +      navigate(`/admin`);
navigate to root

2022-04-20 00:41 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>          console.log(err.message);
remove log now that we have toast (also remove todo comment)

2022-04-20 00:41 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
>        },
Right now when I upload a bad CSV the site breaks completely. I think this should be handled with toasts (ie the site shouldn't crash and an error toast should be shown if possible)

You can do this with try catch

2022-05-02 00:54 UTC, ctc-devops commented on src/components/AddBoxForm/AddBoxForm.jsx
> +      console.log(`Cannot find ${formData.zipcode} in country ${formData.country}`);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-02 00:54 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-02 00:54 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-02 00:54 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +            console.log('cannot find latitude for formData: ', formData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-02 00:54 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +              console.log(rowData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-03 20:38 UTC, claudeisakeeb requested changes
toast provider kinda nutty, just remove all of the log statements now that we have the toast

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>        console.log(`Cannot find ${formData.zipcode} in country ${formData.country}`);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>          navigate('/admin');
should navigate to root (/)

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>          navigate('/admin');
should navigate to root (/)

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>          console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>          console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/ForgotPassword/ForgotPasswordForm.jsx
>        console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/ForgotPassword/ForgotPasswordForm.jsx
>        console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/MarkerInfo/DeleteBoxModal/DeleteBoxModal.jsx
>        console.log(err);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/MarkerInfo/DeleteBoxModal/DeleteBoxModal.jsx
>        console.log(err);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/PickupBoxForm/PickupBoxForm.jsx
>        alert(`Cannot find ${formData.zipcode} in country ${formData.country}`);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/PickupBoxForm/PickupBoxForm.jsx
>        alert(`Cannot find ${formData.zipcode} in country ${formData.country}`);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/PickupBoxForm/PickupBoxForm.jsx
>          console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/PickupBoxForm/PickupBoxForm.jsx
>          console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/RelocateBoxForm/RelocateBoxForm.jsx
>          console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/RelocateBoxForm/RelocateBoxForm.jsx
>          console.log(err.message);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
> +      console.log(err);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
> +      console.log(err);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
>        console.log(err);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
>        console.log(err);
remove

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
>            navigate('/admin');
should navigate to root (/)

2022-05-03 20:38 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
>            navigate('/admin');
should navigate to root (/)

2022-05-04 02:47 UTC, claudeisakeeb requested changes
one more

2022-05-04 02:47 UTC, claudeisakeeb commented on src/components/AddBoxForm/AddBoxForm.jsx
>        console.log(`Cannot find ${formData.zipcode} in country ${formData.country}`);
remove

2022-05-04 02:47 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +              console.log(rowData);
remove

2022-05-04 02:51 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +              console.log(rowData);
nvm this is not part of the PR anways

2022-05-04 02:51 UTC, claudeisakeeb approved these changes, later dismissed
perfectly toasted toast

2022-05-06 22:09 UTC, sylvesteryue approved these changes, later dismissed
LGTM

2022-05-06 22:13 UTC, sylvesteryue approved these changes
lg (toasty) m

2022-05-06 22:21 UTC, merged