upload-csv-high-fidelity-mobile-view
ctc-uci/find-your-anchor-frontend pull request #147
Opened 2022-04-26 17:46 UTC by ctc-devops

- follow Figma designs for Upload CSV mobile view and high fidelity
closes #145

2022-04-27 08:38 UTC, ctc-devops commented on src/components/AddBoxForm/AddBoxForm.jsx
> +      console.log(`Cannot find ${formData.zipcode} in country ${formData.country}`);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-27 08:38 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +          alert('Cannot find latitude/longitude for zipcode. Please click Edit/View file');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-04-27 08:38 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-27 08:38 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +            console.log('cannot find latitude for formData: ', formData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-27 08:38 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +        console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-27 08:38 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +              console.log('Row Data: ', rowData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-28 01:25 UTC, ctc-devops commented on src/components/UploadCSVView/EditableRow/EditableRow.jsx
> +    console.log('editable row mounted');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-28 09:41 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +          alert('Cannot find latitude/longitude for zipcode. Please click View file');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-05-02 19:56 UTC, jeffcheema approved these changes
LGTM!

2022-05-02 21:25 UTC, meghakak requested changes
LGTM for the most part! Awesome work on the high fidelity and mobile view for this feature! Only error is that I'm getting a 500 error when trying to add the boxes (without errors) to the map. Could y'all look into this?

2022-05-03 01:56 UTC, meghakak approved these changes
LGTM - fixed error on backend as mentioned in DMs :)

2022-05-03 01:56 UTC, merged