last transaction
ctc-uci/find-your-anchor-frontend pull request #151
Opened 2022-04-27 21:12 UTC by ctc-devops

- The recency of a transaction is determined by the date on the form submitted by the user (NOT the date the user submitted the form)
- Delete most recent transaction from Box_History
- Only copy box info from Box_History to Anchor_Box after admin approves a box if the date on the box is the most recent
closes #144

2022-04-27 23:30 UTC, ctc-devops commented on src/components/MarkerInfo/DeleteBoxModal/DeleteBoxModal.jsx
> +      console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-30 23:47 UTC, aliu55 requested changes
Code looks good! Just a couple comments about the PickupBox and RelocationBox, and the PR should be good to go.

2022-04-30 23:47 UTC, aliu55 commented on src/components/PickupBox/PickupBox.jsx
> +        coordinates = [0, 0];
Can we set coordinates to null? This way, we can make sure the box doesn't get added to the map because (0,0) is the wrong location for this box.

2022-04-30 23:47 UTC, aliu55 commented on src/components/PickupBox/PickupBox.jsx
> +      let coordinates = await getLatLong(zipCode, country || 'US');
Please remove the 'US' from here because the country is already defined

2022-04-30 23:47 UTC, aliu55 commented on src/components/RelocationBox/RelocationBox.jsx
> +      }
Please refer to the comment in PickupBox

2022-05-01 00:07 UTC, meghakak requested changes
Great work on this PR! Same comments as Ashley :)

2022-05-03 20:05 UTC, claudeisakeeb commented on src/components/RelocationBox/RelocationBox.jsx
> +      }
referred

2022-05-03 20:05 UTC, claudeisakeeb commented on src/components/PickupBox/PickupBox.jsx
> +        coordinates = [0, 0];
set

2022-05-03 20:06 UTC, claudeisakeeb commented on src/components/PickupBox/PickupBox.jsx
> +      let coordinates = await getLatLong(zipCode, country || 'US');
ok, did same thing for relocationbox

2022-05-04 00:15 UTC, meghakak approved these changes
LGTM

2022-05-04 06:18 UTC, aliu55 approved these changes
LGTM

2022-05-04 07:41 UTC, merged