zipcode data dump
ctc-uci/find-your-anchor-frontend pull request #154
Opened 2022-04-30 21:59 UTC by ctc-devops

- Use zip code data dump to verify if zipcode exists in a country instead of the Nominatim API
- Zip code data dump: https://download.geonames.org/export/zip/
closes #141

2022-05-01 02:26 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +        console.log('addToMap: ', formDatas);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-02 21:35 UTC, meghakak requested changes
Code so cleannnn!! Thank you for integrating the zipcode data dump! Just a comment about file naming and this should be good to go.

2022-05-02 21:35 UTC, meghakak commented on src/common/zipcodeDataDump.json
> +{
Can we delete this file? I don't think it's being used.

2022-05-02 21:35 UTC, meghakak commented on src/common/zipcodeDataDump.json
> +{
Actually, let's delete this one and rename allCountries.json to zipcodeDataDump.json. And then update the uses of allCountries.json to the new file name.

2022-05-03 00:31 UTC, jeffcheema approved these changes, later dismissed
LGTM!

2022-05-03 03:42 UTC, meghakak approved these changes
LGTM

2022-05-03 03:45 UTC, merged