fix upload csv bugs
ctc-uci/find-your-anchor-frontend pull request #178
Opened 2022-05-10 23:43 UTC by ctc-devops

- pick 3 bugs to fix for Upload CSV from the [Find You Bugs](https://docs.google.com/document/d/1f3dqxzRCiNGZ2yWU_FtyrNNjUOFZ8lxiEuXo958NVDM/edit#heading=h.57deawcull14) doc
- comment the 3 bugs fixed in the PR comments
closes #176

2022-05-11 02:08 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +              console.log('Accordion Props: ', accordionProps);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-11 22:48 UTC, Preston-Young commented
Fixed 3 bugs for Upload CSV:

1. Bug #22: Upload CSV mobile: Pagination controls should be at bottom of the page 
2. Bug #39: Upload CSV preview box should be outlined in red if there is an error
3. Bug #42: Clicking Add to Map for mobile upload CSV view doesn’t open first accordion row with error

2022-05-13 16:52 UTC, claudeisakeeb requested changes
Looks good :D 
Just one comment regarding the pagination controls hovering

2022-05-13 16:52 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
>        <CSVViewTablePagination
Bit of a nit but the pagination controls are still hovering for me: 
![image](https://user-images.githubusercontent.com/47193525/168331232-f6250e91-2da8-4562-9ac2-906aed53cd00.png)

You can try giving the controller position sticky and then calculate the height of the csv upload table with something like calc(100vh - navBarHeight - tableHeaderHeight - paginationControllerHeight) so that it fills up the rest of the screen

2022-05-14 16:59 UTC, aliu55 commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
>        <CSVViewTablePagination
genius

2022-05-14 17:11 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
>        <CSVViewTablePagination
no you

2022-05-14 17:12 UTC, claudeisakeeb submitted a review, later dismissed
sicko mode

2022-05-14 20:55 UTC, meghakak requested changes
LGTM for the most part! Just a couple comments on changing the hardcoded colors to use the colors defined in vars.css. While you will be changing all the colors in another style guide PR, it is better to start using the vars.css colors for any colors y'all add going forward.

2022-05-14 20:55 UTC, meghakak commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +                    borderColor={rowData.values.error && 'red'}
Can we use the warning color in [vars.css](https://github.com/ctc-uci/find-your-anchor-frontend/blob/dev/src/common/vars.css) instead of red?

2022-05-14 20:55 UTC, meghakak commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +                            _expanded={{ bg: 'white' }}
Same here, please use the colors in vars.css

2022-05-18 09:03 UTC, claudeisakeeb approved these changes
pog

2022-05-18 19:52 UTC, meghakak approved these changes
LGTM

2022-05-18 19:52 UTC, merged