move-upload-csv-to-frontend
ctc-uci/find-your-anchor-frontend pull request #179
Opened 2022-05-11 22:47 UTC by ctc-devops

- move the logic for Upload CSV from the frontend to the backend
closes #172

2022-05-13 07:48 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +    console.log('Response: ', response);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-13 07:48 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +    console.log('Row Data: ', rowData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-13 07:48 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +    console.log('Box Numbers: ', boxNumbers);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-13 07:48 UTC, ctc-devops commented on src/components/UploadCSV/UploadCSV.jsx
> +    console.log('Num Errors: ', numErrors);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-16 00:26 UTC, claudeisakeeb requested changes
Great job, just some nits

2022-05-16 00:26 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
> +        // formDatas[index].longitude = zipcodeDataDump[countryCode][formData.zipCode].long;
remove comments d8^)

2022-05-16 00:26 UTC, claudeisakeeb commented on src/components/UploadCSV/UploadCSV.jsx
> +// import zipcodeDataDump from '../../common/zipcodeDataDump.json';
remove

2022-05-16 20:11 UTC, meghakak requested changes
Code looks amazing!! Ty for doing all the refactoring for this.
Just one error I'm seeing - the mobile view for the csv view table (with errors) is not functioning as intended. When I click "Add to Map", it does not open the first box with an error, but instead it shows the error message in the top left corner. Could y'all look into this?

2022-05-16 20:18 UTC, claudeisakeeb requested changes
One more thing I missed on the last review :D

2022-05-16 20:18 UTC, claudeisakeeb commented on src/components/UploadCSVView/EditableRow/EditableRow.jsx
>    isError: PropTypes.bool.isRequired,
On line 179 of this file the country placeholder is "e.g. 90210," can we change this to a country? 8^)

2022-05-17 17:16 UTC, aliu55 commented on src/components/UploadCSVView/EditableRow/EditableRow.jsx
>    isError: PropTypes.bool.isRequired,
8)

2022-05-17 17:17 UTC, Preston-Young commented
> 

Hi Megha, this error should actually be fixed by [this PR](https://github.com/ctc-uci/find-your-anchor-frontend/pull/178) because clicking Add to Map will now open the first row on Mobile that has an error, so the tooltip should show up in the right place.

2022-05-18 04:36 UTC, meghakak commented
> > 
> 
> Hi Megha, this error should actually be fixed by [this PR](https://github.com/ctc-uci/find-your-anchor-frontend/pull/178) because clicking Add to Map will now open the first row on Mobile that has an error, so the tooltip should show up in the right place.

Gotcha!

2022-05-18 04:36 UTC, meghakak approved these changes
LGTM

2022-05-18 04:41 UTC, claudeisakeeb approved these changes
super saiyan

2022-05-18 04:41 UTC, merged