3 bug dash
ctc-uci/find-your-anchor-frontend pull request #185
Opened 2022-05-12 23:08 UTC by ctc-devops

- Pick 3 bugs from the [Find Your Bugs](https://docs.google.com/document/d/1f3dqxzRCiNGZ2yWU_FtyrNNjUOFZ8lxiEuXo958NVDM/edit#) document
- Comment which 3 bugs you fix
- Mark the 3 fixed bugs as done on the document
closes #171

2022-05-13 00:08 UTC, claudeisakeeb commented
FIXED BUGS 1, 2, 6, 7, 9, 10, 26, 28 (you are welcome)

2022-05-15 01:54 UTC, aliu55 approved these changes
LGTM

2022-05-15 02:22 UTC, aliu55 requested changes
Looks good! Just one tiny comment

2022-05-15 02:22 UTC, aliu55 commented on src/components/MarkerInfo/BoxInfo/BoxInfo.module.css
> +  right: 10px;
Bit of a nitpick but the delete box is just slightly off

![image](https://user-images.githubusercontent.com/70079773/168454445-ffd283e1-e929-4728-bfcd-ad44d302b13f.png)

2022-05-15 02:40 UTC, claudeisakeeb commented on src/components/MarkerInfo/BoxInfo/BoxInfo.module.css
> +  right: 10px;
i shifted it more to the left but it's a bit weird because of the scrollbar, let us know what you think

2022-05-15 04:18 UTC, aliu55 commented on src/components/MarkerInfo/BoxInfo/BoxInfo.module.css
> +  right: 10px;
beautiful

2022-05-15 05:05 UTC, aliu55 submitted a review, later dismissed
LGTM

2022-05-15 05:15 UTC, meghakak requested changes
Thanks for fixing so many bugs this sprint :) Couple comments on this PR, lmk if y'all have any questions about them. Also, since y'all are fixing bug 6 in this PR, could you make the footer sticky on the About page as well?

2022-05-15 05:15 UTC, meghakak commented on src/components/MarkerInfo/BoxInfo/BoxInfo.jsx
> +                )}
If there is an empty field, then we shouldn't show the label for that field either. Can we make that edit here?

2022-05-15 05:15 UTC, meghakak commented on src/components/MarkerInfo/BoxInfo/BoxInfo.jsx
> +                )}
Same with the rest of the fields for BoxInfo

2022-05-15 05:15 UTC, meghakak commented on src/pages/Dashboard/Dashboard.jsx
> +            >
Not sure if this is the right code block to comment on, but could we make the right sidebar slide out when the user clicks on the X button to close the sidebar? The left sidebar slides to open and close but the right sidebar only slides on open.

2022-05-15 05:32 UTC, claudeisakeeb commented on src/components/MarkerInfo/BoxInfo/BoxInfo.jsx
> +                )}
woops, fixed

2022-05-15 05:55 UTC, claudeisakeeb commented on src/pages/Dashboard/Dashboard.jsx
> +            >
> Thanks for fixing so many bugs this sprint :) Couple comments on this PR, lmk if y'all have any questions about them. Also, since y'all are fixing bug 6 in this PR, could you make the footer sticky on the About page as well?

made it stick

2022-05-15 05:55 UTC, claudeisakeeb commented
> Thanks for fixing so many bugs this sprint :) Couple comments on this PR, lmk if y'all have any questions about them. Also, since y'all are fixing bug 6 in this PR, could you make the footer sticky on the About page as well?

made footer on about page sticky

2022-05-15 05:59 UTC, claudeisakeeb commented on src/pages/Dashboard/Dashboard.jsx
> +            >
We're structured it the exact same way that we structured the left sidebar so I really have no idea why it doesn't show the closing animation lol

2022-05-16 00:21 UTC, meghakak approved these changes
LGTM

2022-05-16 00:23 UTC, aliu55 approved these changes
LGTM

2022-05-16 00:24 UTC, merged