add pagination to export csv
ctc-uci/find-your-anchor-frontend pull request #196
Opened 2022-05-15 21:27 UTC by ctc-devops

- add pagination to export csv preview table

closes #194

2022-05-18 01:09 UTC, ctc-devops commented on src/components/ExportCSV/CSVPreview/CSVPreview.jsx
> +                console.log('[CSVPreview] rowData: ', rowData);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-18 01:09 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +  console.log(columns);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-18 01:09 UTC, ctc-devops commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.jsx
> +  console.log(data);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-20 00:20 UTC, claudeisakeeb requested changes
lmk if you have comments :)

2022-05-20 00:20 UTC, claudeisakeeb commented on src/components/ExportCSV/CSVPreview/CSVPreview.jsx
> +import CSVViewTablePagination from '../../UploadCSVView/CSVViewTable/CSVViewTablePagination';
If you use the same CSVViewTable as UploadCSV maybe it'll be better to move it into the common folder so it's easier to know where to go to look if something breaks?

2022-05-20 00:20 UTC, claudeisakeeb commented on src/components/UploadCSVView/CSVViewTable/CSVViewTable.module.css
> +  height: calc(100vh - 210px);
Can we make the pagination controller sticky bottom for export CSV?
![image](https://user-images.githubusercontent.com/47193525/169424330-cc32d7c1-21ba-4d26-9281-ab1bbe53d5f0.png)
Also, UploadCSV overflows with this change
![image](https://user-images.githubusercontent.com/47193525/169424509-ecd362df-2d3f-472c-a2f5-7b26791fb3f0.png)

2022-05-20 01:10 UTC, meghakak requested changes
LGTM overall - ty for adding pagination to export CSV as well! Glad that y'all were able to reuse the upload CSV pagination for this.

One thing - could we change the number part of the "Go to page _" section to be underlined as shown in the figma? This would apply to upload CSV as well and y'all _might_ already be working on this so just lmk if it's in a separate PR :)

2022-05-20 01:10 UTC, meghakak commented on src/components/ExportCSV/CSVPreview/CSVPreview.jsx
> +import CSVViewTablePagination from '../../UploadCSVView/CSVViewTable/CSVViewTablePagination';
Yeah I agree that moving CSVViewTablePagination component to /common would be good. Maybe add a folder under /common named TablePagination with that component.

2022-05-20 17:56 UTC, meghakak commented
> LGTM overall - ty for adding pagination to export CSV as well! Glad that y'all were able to reuse the upload CSV pagination for this.
> 
> One thing - could we change the number part of the "Go to page _" section to be underlined as shown in the figma? This would apply to upload CSV as well and y'all _might_ already be working on this so just lmk if it's in a separate PR :)

jk about the "Go to page _" part since that's been added in #195

2022-05-24 04:14 UTC, meghakak requested changes
Could we take out the "Show #" part at the top for mobile view? I know there isn't a mockup for this, but that part is pushing the "Export CSV" button off screen. Also, since the "Show #" isn't in the mobile view for Upload CSV, I think it makes sense to remove that for Export CSV mobile view as well.

2022-05-24 23:39 UTC, meghakak approved these changes
LGTM

2022-05-25 02:59 UTC, meghakak approved these changes, later dismissed
LGTM

2022-05-25 03:12 UTC, claudeisakeeb requested changes
Looks great, just one more thing 
Current toast for no records matching:
![image](https://user-images.githubusercontent.com/47193525/170171916-354b8925-b11f-4d17-abc9-2b62b3f85133.png)
Figma toast:
![image](https://user-images.githubusercontent.com/47193525/170171965-b1537325-2663-4792-8c8f-2a0b3895145f.png)

2022-05-26 18:07 UTC, meghakak approved these changes
LGTM

2022-05-26 18:22 UTC, claudeisakeeb approved these changes
poetry in motion

2022-05-26 18:28 UTC, merged