all admin general bugs
ctc-uci/find-your-anchor-frontend pull request #203
Opened 2022-05-17 22:35 UTC by ctc-devops

- Fix All General & Admin Dashboard Bugs
- Make sure that everything matches the Figma
closes #190

2022-05-18 22:23 UTC, ctc-devops commented on src/components/Map/Map.jsx
> +    console.log(cluster);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-05-20 00:46 UTC, claudeisakeeb commented
As discussed we're leaving the marker clusters as is. Also we made a decision to just keep the marker clusters as is because
 1. we can't make it look like the tooltip thing in the Figma and 
 2. teal on white looks way worse than white on teal (just trust us)

2022-05-21 02:39 UTC, aliu55 requested changes
Code review from me and Megha:

Good job on this sprint! We noticed that Bug 30 is marked as Not a Bug, but we still saw an x button on the box details in the mobile view. Could we please remove the x button? Also for Bug 59, it's marked as fixed but the rejected image still shows up in right sidebar. Could y'all look into this?

2022-05-21 02:39 UTC, aliu55 commented on src/common/utils.jsx
> +    // }
Please uncomment this

2022-05-21 02:40 UTC, meghakak requested changes
^^

2022-05-26 00:41 UTC, jennymylee commented on src/common/utils.jsx
> +    // }
thank you for this

2022-05-27 08:25 UTC, meghakak approved these changes
LGTM

2022-05-27 15:50 UTC, aliu55 approved these changes
LGTM

2022-05-27 23:20 UTC, merged