navbar footer bugs
ctc-uci/find-your-anchor-frontend pull request #205
Opened 2022-05-19 18:16 UTC by ctc-devops

Fix all bugs on the [Find Your Shrek](https://docs.google.com/document/d/1f3dqxzRCiNGZ2yWU_FtyrNNjUOFZ8lxiEuXo958NVDM/edit?pli=1#heading=h.pylkt3kz9rjv) doc that are related to the navbar and footer.
closes #192

2022-05-19 21:51 UTC, dgardezi commented
fixed bugs: 4, 25, 44

2022-05-23 06:29 UTC, aliu55 requested changes
Good job on fixing the bugs! Just a small comment on the navbar. Also, please resolve the merge conflict :)

2022-05-23 06:29 UTC, aliu55 commented on src/components/NavBar/NavBar.module.css
> +  background-color: var(--color-white);
Hmm the navbar is still missing a box shadow (Bug 4). You might just need to change the background color to something else.

2022-05-23 07:47 UTC, aliu55 approved these changes
LGTM

2022-06-07 18:14 UTC, sylvesteryue approved these changes
LGTM

2022-06-07 18:14 UTC, merged