export csv to rhf
ctc-uci/find-your-anchor-frontend pull request #41
Opened 2022-02-15 21:29 UTC by ctc-devops

- [RHF w/ Yup schema validation example](https://react-hook-form.com/get-started#SchemaValidation)
- [RHF API documentation](https://react-hook-form.com/api)
- [Yup Documentation](https://github.com/jquense/yup)
closes #40

2022-02-15 23:36 UTC, ctc-devops commented on src/pages/ExportCSV/RHFTest.jsx
> +  const onSubmit = data => alert(JSON.stringify(data, null, 2));
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-02-16 00:37 UTC, ctc-devops commented on src/pages/ExportCSV/RHFTest/RHFTest.jsx
> +  const onSubmit = data => alert(JSON.stringify(data, null, 2));
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-02-17 03:59 UTC, ctc-devops commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +    alert(JSON.stringify(data, null, 2));
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-02-26 02:22 UTC, ctc-devops commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +  console.log(boxDetails);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-26 02:22 UTC, ctc-devops commented on src/index.jsx
> +import ExportCSVOld from './pages/ExportCSV/ExportCSVOld';
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'ExportCSVOld' is defined but never used.

2022-02-26 02:22 UTC, ctc-devops commented on src/index.jsx
> +import RHFTest from './pages/ExportCSV/RHFTest/RHFTest';
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'RHFTest' is defined but never used.

2022-03-31 07:16 UTC, meghakak requested changes
Great work these past couple sprints! The Export CSV feature is super cool and y'all did an awesome job implementing it :) I've left a few comments below - please take a look and let me know if y'all have any questions. Also, could we add the confirmation modal after exporting as shown on the Figma? You can use the common modal that Ashley created.

In addition, here are a couple bugs I found:
1. Filtering by custom zip code or date crashes the app (I'm getting 500 errors for these)
2. Ordering boxes chronologically (by date) does not seem to be working as intended

2022-03-31 07:16 UTC, meghakak commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +    // reset();
nit: remove?

2022-03-31 07:16 UTC, meghakak commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +    // setFormValues(getValues());
Is this still needed? The preview is shown after the user clicks on "Preview CSV" so I don't think we would need to update anything as the user is changing the filters anymore.

2022-03-31 07:16 UTC, meghakak commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +    // setFormValues(data);
Remove this as well if we are removing the other setFormValues call

2022-03-31 07:16 UTC, meghakak commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +                          className={styles[`date-picker${errors?.singleDate ? '-error' : ''}`]}
Let's change this to something like `{styles[${errors?.singleDate ? 'date-picker-error' : 'date-picker'}]}` - this makes this line a bit easier to read.

2022-03-31 07:16 UTC, meghakak commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +                              className={styles[`date-picker${errors?.startDate ? '-error' : ''}`]}
Same here - change this to `{styles[${errors?.startDate? 'date-picker-error' : 'date-picker'}]}`

2022-03-31 07:16 UTC, meghakak commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +                              className={styles[`date-picker${errors?.startDate ? '-error' : ''}`]}
Same for the endDate

2022-03-31 07:16 UTC, meghakak commented on src/pages/CSVPreviewPage/CSVPreviewPage.module.css
> +  /* border: 1px solid red; */
nit: please remove if not needed

2022-03-31 07:16 UTC, meghakak commented on src/pages/ExportCSV/ExportCSV.module.css
> +.export-csv-wrapper {
This page contains the same styling as CSVPreviewPage.module.css. Please remove the other copied file and just use this one for both jsx files that need the styling.

2022-03-31 07:16 UTC, meghakak commented on src/pages/ExportCSV/ExportCSVOld.jsx
> +import React from 'react';
Please delete this file if it is no longer being used

2022-04-06 05:14 UTC, meghakak submitted a review, later dismissed
LGTM

2022-04-07 02:28 UTC, sylvesteryue approved these changes, later dismissed
LGTM

2022-04-07 02:35 UTC, ctc-devops commented on src/components/ExportCSV/ExportCSVForm/ExportCSVForm.jsx
> +      console.log('no matching records');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-07 02:35 UTC, ctc-devops commented on src/index.jsx
> +import CSVPreviewPage from './pages/CSVPreviewPage/CSVPreviewPage';
🚫 **[eslint]** <[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'CSVPreviewPage' is defined but never used.

2022-04-07 02:35 UTC, ctc-devops commented on src/index.jsx
> +
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `············`
```suggestion

```

2022-04-07 03:00 UTC, sylvesteryue approved these changes
LGTM

2022-04-07 03:01 UTC, merged