add box to rhf
ctc-uci/find-your-anchor-frontend pull request #44
Opened 2022-02-18 07:30 UTC by ctc-devops

[React Hook Form](https://react-hook-form.com/)
closes #43

2022-02-18 09:11 UTC, ctc-devops commented on src/components/BoxForm/BoxForm.jsx
> +    alert(JSON.stringify(formData, null, 2));
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-02-18 09:53 UTC, ZubairSidhu commented on src/components/BoxForm/BoxForm.jsx
> +    date: yup
How should date be stored? Currently it is in ISO format.

2022-02-18 22:10 UTC, ZubairSidhu commented on src/components/BoxForm/BoxForm.jsx
> +    date: yup
Going with MM/DD/YYYY as per Sylvester's suggestion

2022-02-19 01:06 UTC, meghakak requested changes
Thanks for integrating react hook forms! Just a couple small comments.

2022-02-19 01:06 UTC, meghakak commented on src/components/BoxForm/BoxFormUtils.js
> +};
Can we move this function to the common utils file?

2022-02-19 01:06 UTC, meghakak commented on src/components/BoxForm/BoxForm.jsx
> +      .typeError('Invalid date, please enter a date'),
nit: "Invalid date, please enter a valid date." to keep it consistent with zipcode error message

2022-02-19 01:06 UTC, meghakak commented on src/components/BoxForm/BoxForm.jsx
> +import React, { useState } from 'react';
I should have brought this up in the last PR on add box form, but is BoxForm.jsx only going to be used for the Add Box Form? If so, then it may be better for us to rename this file to AddBoxForm.jsx and for the current /pages/AddBoxForm/AddBoxForm.jsx to be renamed to AddBoxFormPage.jsx or something along those lines. Another solution is to just put everything in this file in /pages/AddBoxForm/AddBoxForm.jsx since this is the only content on that page other than header and footer. Let me know your thoughts on this.

2022-02-19 01:21 UTC, ZubairSidhu commented on src/components/BoxForm/BoxFormUtils.js
> +};
Done!

2022-02-19 01:21 UTC, ZubairSidhu commented on src/components/BoxForm/BoxForm.jsx
> +      .typeError('Invalid date, please enter a date'),
Fixed!

2022-02-19 01:29 UTC, ZubairSidhu commented on src/components/BoxForm/BoxForm.jsx
> +import React, { useState } from 'react';
I would prefer to keep pages and components separated. Renamed files:
`pages/AddBoxForm/AddBoxForm.jsx` -> `pages/AddBoxForm/AddBoxFormPage.jsx`
`components/BoxForm/BoxForm.jsx` -> `components/AddBoxForm/AddBoxForm.jsx`

2022-02-19 04:41 UTC, meghakak submitted a review, later dismissed
LGTM

2022-02-19 06:38 UTC, sylvesteryue requested changes

2022-02-19 06:38 UTC, sylvesteryue commented on src/components/AddBoxForm/AddBoxFormUtils.js
> +    return isValidZip(value) ? true : createError({ path, message: 'Not a valid zip code' });
Can we change this to an arrow function?

2022-02-19 07:50 UTC, ctc-devops commented on src/common/utils.jsx
> +    console.error(`[Axios] FYABackend error: ${JSON.stringify(error.toJSON(), null, 2)}`);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-19 07:51 UTC, ZubairSidhu commented on src/components/AddBoxForm/AddBoxFormUtils.js
> +    return isValidZip(value) ? true : createError({ path, message: 'Not a valid zip code' });
Can't use an arrow function here, as custom validators in yup need access to the `this` keyword, which isn't available in arrow functions.

2022-02-19 08:04 UTC, meghakak approved these changes
LGTM

2022-02-19 11:31 UTC, sylvesteryue approved these changes
LGTM

2022-02-19 11:31 UTC, merged