login register form
ctc-uci/find-your-anchor-frontend pull request #53
Opened 2022-02-23 19:10 UTC by ctc-devops

- Follow Figma designs
- Use React Hook Form: https://react-hook-form.com/advanced-usage#CustomHookwithResolver
- Don't worry about backend until auth is merged
closes #50

2022-02-23 21:54 UTC, ctc-devops commented on src/components/Login/LoginForm.jsx
> +    alert(JSON.stringify(data));
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-02-27 23:26 UTC, ctc-devops commented on src/components/Register/RegisterForm.jsx
> +    alert(JSON.stringify(data));
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-01 09:01 UTC, meghakak requested changes
Thank you for making the general input components and for finishing early this sprint!

It seems like the styling for the forms get wonky when the user zooms in too much - for me, the Login and Register forms are going off screen. I might be wrong, but I believe it has something to do with "height: 100%" being used in multiple places on the same page. Please try to fix this styling and let me know if y'all would like me to look into it as well.

2022-03-01 09:01 UTC, meghakak commented on src/components/Inputs/PasswordInput.jsx
> +            </a>
Can we use a React Link component instead of an a tag?
https://v5.reactrouter.com/web/api/Link

2022-03-01 09:01 UTC, meghakak commented on src/components/Inputs/TextInputs.jsx
> +import React from 'react';
What is the difference between TextInputs.jsx and TextInput.jsx? Are we using both of them or just one?

2022-03-01 09:01 UTC, meghakak commented on src/components/Login/LoginForm.jsx
> +        <div align="right">
nit: Please move styling to css file

2022-03-03 00:08 UTC, sylvesteryue reviewed
Great job on this as well, I just want to add upon Megha's comment on the height styling that for me, maybe due to the height of my screen, the Register title and FYA logo overlaps on the top

2022-03-03 20:10 UTC, dgardezi commented on src/components/Inputs/TextInputs.jsx
> +import React from 'react';
Removed TextInputs.jsx, file was renamed but I didn't commit that change last time.

2022-03-03 20:18 UTC, dgardezi commented
I think all the issues you guys brought up have been addressed, but let me know if there is still anything left to correct. I replaced the absolute positioning of the logo with flexbox so the main problem should be resolved now.

2022-03-06 05:45 UTC, meghakak submitted a review, later dismissed
LGTM

2022-03-06 19:43 UTC, meghakak approved these changes, later dismissed
LGTM

2022-03-08 20:34 UTC, sylvesteryue approved these changes, later dismissed
LGTM

2022-03-08 20:36 UTC, sylvesteryue approved these changes

2022-03-08 20:42 UTC, merged