layout component
ctc-uci/find-your-anchor-frontend pull request #57
Opened 2022-02-26 04:45 UTC by ctc-devops

Layout component to wrap all pages that need access to the header.
closes #56

2022-03-02 05:06 UTC, meghakak requested changes
Just one small change for the navbar! Thank you for picking up this task :)

2022-03-02 05:06 UTC, meghakak commented on src/components/NavBar/NavBar.jsx
>        </div>
Could we add a Link tag for this image to link to the home page ('/') when clicked?

2022-03-02 07:13 UTC, meghakak approved these changes
LGTM

2022-03-03 05:11 UTC, sylvesteryue approved these changes
LGTM

2022-03-03 05:11 UTC, merged