aap emailing
ctc-uci/find-your-anchor-frontend pull request #61
Opened 2022-03-02 22:11 UTC by ctc-devops

- Find emailing API to use for sending emails (maybe check firebase if there's a way to email directly using this API)
- Send emails when admin approves, requests changes, or rejects box submission
- Communicate with design on what each email should contain
closes #48

2022-03-02 23:48 UTC, ctc-devops commented on src/components/Email/EmailForm.jsx
> +        alert('Email sent, awesome!');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-02 23:48 UTC, ctc-devops commented on src/components/Email/EmailForm.jsx
> +        alert('Oops, something went wrong. Try again');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-06 00:05 UTC, ctc-devops commented on src/common/utils.jsx
> +      alert('Email sent, awesome!');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-06 00:05 UTC, ctc-devops commented on src/common/utils.jsx
> +      alert('Oops, something went wrong. Try again');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-10 02:05 UTC, meghakak requested changes
Code looks good, but the emailing is not working on my end. I'm also getting a lot of warnings in the console anytime I load the admin dashboard - could y'all look into this if you have time?

2022-03-10 02:05 UTC, meghakak commented on src/components/Email/EmailForm.jsx
> +// import React, { useState } from 'react';
Can we remove this file? Unless there is any reason to keep it for future reference

2022-03-10 02:05 UTC, meghakak commented on EmailKey.js
> +export default { USER_ID: ``, TEMPLATE_ID: `` };
Are these being used anywhere?

2022-03-10 02:52 UTC, jennymylee commented on src/components/Email/EmailForm.jsx
> +// import React, { useState } from 'react';
removed

2022-03-10 02:53 UTC, jennymylee commented on EmailKey.js
> +export default { USER_ID: ``, TEMPLATE_ID: `` };
we deleted this file

2022-03-10 02:54 UTC, ctc-devops commented on src/index.jsx
> +import EmailForm from './components/Email/EmailForm';
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './components/Email/EmailForm'.

2022-03-10 02:54 UTC, ctc-devops commented on src/index.jsx
> +import EmailForm from './components/Email/EmailForm';
🚫 **[eslint]** <[import/extensions](https://github.com/import-js/eslint-plugin-import/blob/v2.25.4/docs/rules/extensions.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing file extension for "./components/Email/EmailForm"

2022-03-10 04:25 UTC, jennymylee commented
> Code looks good, but the emailing is not working on my end. I'm also getting a lot of warnings in the console anytime I load the admin dashboard - could y'all look into this if you have time?

In order for the emailing to work, you would have to include a file called [emailConfig.json](https://drive.google.com/drive/u/0/folders/1BbWW03N1LzGRN8nDWlFhQ3s2x9noH8nW) on our aaa-emailing branch in the backend. I just tested this and everything seems to work correctly. Please let us know if you run into problems.

2022-03-10 06:53 UTC, claudeisakeeb commented
> > Code looks good, but the emailing is not working on my end. I'm also getting a lot of warnings in the console anytime I load the admin dashboard - could y'all look into this if you have time?
> 
> In order for the emailing to work, you would have to include a file called [emailConfig.json](https://drive.google.com/drive/u/0/folders/1BbWW03N1LzGRN8nDWlFhQ3s2x9noH8nW) on our aaa-emailing branch in the backend. I just tested this and everything seems to work correctly. Please let us know if you run into problems.

^^^^ would it be better if we move the email credentials into the env file?

2022-03-10 11:02 UTC, sylvesteryue commented
> > > Code looks good, but the emailing is not working on my end. I'm also getting a lot of warnings in the console anytime I load the admin dashboard - could y'all look into this if you have time?
> > 
> > 
> > In order for the emailing to work, you would have to include a file called [emailConfig.json](https://drive.google.com/drive/u/0/folders/1BbWW03N1LzGRN8nDWlFhQ3s2x9noH8nW) on our aaa-emailing branch in the backend. I just tested this and everything seems to work correctly. Please let us know if you run into problems.
> 
> ^^^^ would it be better if we move the email credentials into the env file?

That was what I had in mind, I think it would be good enough since the rest of the credentials for other services are in that file as well and we should keep it all in one place

2022-03-10 21:42 UTC, claudeisakeeb commented
> > > > Code looks good, but the emailing is not working on my end. I'm also getting a lot of warnings in the console anytime I load the admin dashboard - could y'all look into this if you have time?
> > > 
> > > 
> > > In order for the emailing to work, you would have to include a file called [emailConfig.json](https://drive.google.com/drive/u/0/folders/1BbWW03N1LzGRN8nDWlFhQ3s2x9noH8nW) on our aaa-emailing branch in the backend. I just tested this and everything seems to work correctly. Please let us know if you run into problems.
> > 
> > 
> > ^^^^ would it be better if we move the email credentials into the env file?
> 
> That was what I had in mind, I think it would be good enough since the rest of the credentials for other services are in that file as well and we should keep it all in one place

moved

2022-03-11 22:18 UTC, meghakak approved these changes, later dismissed
LGTM! Thanks for moving emailConfig vars to .env - I was using the old emailConfig.js which is why the emailing wasn't working on my end. Awesome work on this PR :)

2022-03-17 00:08 UTC, ctc-devops commented on src/common/utils.jsx
> +    alert('Email sent, awesome!');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-17 00:08 UTC, ctc-devops commented on src/common/utils.jsx
> +    alert('Oops, something went wrong. Try again');
⚠️ **[eslint]** <[no-alert](https://eslint.org/docs/rules/no-alert)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected alert.

2022-03-17 00:09 UTC, claudeisakeeb commented on src/common/utils.jsx
> +    alert('Oops, something went wrong. Try again');
gonna resolve bc this will be replaced with toast

2022-03-17 00:09 UTC, claudeisakeeb commented on src/common/utils.jsx
> +    alert('Email sent, awesome!');
gonna resolve bc this will be replaced with toast

2022-03-17 00:22 UTC, meghakak approved these changes
LGTM

2022-03-18 19:53 UTC, sylvesteryue approved these changes
LGTM

2022-03-18 19:53 UTC, merged