search box
ctc-uci/find-your-anchor-frontend pull request #86
Opened 2022-04-03 23:27 UTC by ctc-devops

Add the ability to search for a specific box number to the search bar on the admin and general user dashboard. Once the user searches for a box number, that box should open and the map should zoom into that box's zip code.
closes #70

2022-04-09 05:20 UTC, ctc-devops commented on src/components/AdminMarkerInfo/BoxInfo/BoxInfo.jsx
> +      console.log(selectedBox);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-09 05:21 UTC, claudeisakeeb commented on src/components/AdminMarkerInfo/BoxInfo/BoxInfo.jsx
> +      console.log(selectedBox);
no

2022-04-14 06:18 UTC, jeffcheema requested changes

2022-04-14 06:18 UTC, jeffcheema commented on src/components/Map/Map.jsx
> +      searchUrl: 'http://localhost:3001/anchorBox/search',
We might want to use environmental variables here since in production the URL will be different!

2022-04-14 06:18 UTC, jeffcheema commented on src/components/AdminMarkerInfo/BoxInfo/BoxInfo.jsx
> +  const [boxHolderName, setBoxHolderName] = useState('Loading...');
Maybe use a CONST loadingString = 'Loading..' and pass that in on the useStates. 
I know its a nitpick but might increase #performance by like 0.05 ms

2022-04-14 16:52 UTC, claudeisakeeb commented on src/components/Map/Map.jsx
> +      searchUrl: 'http://localhost:3001/anchorBox/search',
changed and updated frontend env file

2022-04-14 16:52 UTC, claudeisakeeb commented on src/components/Map/Map.jsx
> +      searchUrl: 'http://localhost:3001/anchorBox/search',
changed and updated frontend env

2022-04-14 16:55 UTC, claudeisakeeb commented on src/components/AdminMarkerInfo/BoxInfo/BoxInfo.jsx
> +  const [boxHolderName, setBoxHolderName] = useState('Loading...');
XD

2022-04-14 17:19 UTC, ctc-devops commented on src/components/AdminMarkerInfo/DeleteBoxModal/DeleteBoxModal.jsx
> +        console.log(deletedBox);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-15 03:26 UTC, meghakak submitted a review, later dismissed
LGTM sheesh awesome work on the search bar!

2022-04-16 19:23 UTC, jeffcheema submitted a review, later dismissed

2022-04-16 20:23 UTC, meghakak approved these changes
LGTM

2022-04-16 21:57 UTC, jeffcheema approved these changes
LGTM!

2022-04-16 21:57 UTC, merged