fix 3 admin approval process bugs pt 1
ctc-uci/find-your-anchor-frontend pull request #92
Opened 2022-04-05 23:11 UTC by ctc-devops

Please fix bugs 2, 3, and 7 on the [dogfooding doc](https://docs.google.com/document/d/12VIkn9-iet9nRUiLaQjT_Y9oR2ggOaREwxJ4twXSYjo/edit#)
closes #80

2022-04-08 17:29 UTC, ctc-devops commented on src/components/RelocationBox/RelocationBox.jsx
> +    console.log(user);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-04-11 15:57 UTC, claudeisakeeb requested changes
Good job, only a few nits and bugs to address

2022-04-11 15:57 UTC, claudeisakeeb commented on src/components/RelocationBox/RelocationBox.jsx
> +  const getStatusMessage = () => {
Can we color these like in the figma?

One way you can do this is by moving the <\h4\> tags into the returns of this function and give each version a different class name. Also same thing for pick up boxes

2022-04-11 15:57 UTC, claudeisakeeb commented on src/components/BoxApproval/BoxApproval.jsx
>  const BoxApproval = () => {
I'm not sure if you get this bug but right now when I refresh the admin dashboard, click on pending changes, and then click on under review, box #1 shows up for a second before disappearing.

I believe you can fix this by not calling fetchBoxes(status, true) when status === 'pending changes' (line 91)

2022-04-11 15:57 UTC, claudeisakeeb commented on src/components/PickupBox/PickupBox.jsx
> +    if (status === 'evaluated' && approved === false) {
super nit: you can shorten approved === false to !approved. Also please convert this to if else

2022-04-11 15:57 UTC, claudeisakeeb commented on src/components/PickupBox/PickupBox.jsx
> +  const getStatusMessage = () => {
super nit: you can shorten approved === false to !approved. Also please convert this to if else

2022-04-11 20:16 UTC, meghakak commented on src/components/PickupBox/PickupBox.jsx
> +    if (status === 'evaluated' && approved === false) {
Eslint returns an error when we do if else here because we are returning something for each condition. Same with getStatusMessage.

2022-04-19 20:29 UTC, merylmarasigan commented on src/components/PickupBox/PickupBox.jsx
> +  const getStatusMessage = () => {
fixed!

2022-04-19 20:29 UTC, merylmarasigan commented on src/components/PickupBox/PickupBox.jsx
> +    if (status === 'evaluated' && approved === false) {
this has been fixed!

2022-04-19 20:39 UTC, merylmarasigan commented on src/components/RelocationBox/RelocationBox.jsx
> +  const getStatusMessage = () => {
fixed!

2022-04-19 20:49 UTC, merylmarasigan commented on src/components/BoxApproval/BoxApproval.jsx
>  const BoxApproval = () => {
this has been fixed!

2022-04-20 04:58 UTC, claudeisakeeb approved these changes
cut the check

2022-04-22 01:05 UTC, sylvesteryue approved these changes
LGTM

2022-04-22 01:06 UTC, merged